# Full path to your log file or directory (mandatory)
:location: "/home/Alice/irc/logs/#channel.log"

# Full path to generated .html file
:save_location: 

# Full path to database file
:database_location: 

# Page info in the header of generated .html
:title: 
:description: 

# Scale for the heatmap (integer)
:heatmap_interval:

# Ignore list
:ignore:
  # - somebot
  # - otherbot

# Combine nick names for people who use multiple
:correct:
  # joebloggs:
  #   - joebloggs_away
  #   - joebloggs_phone

# Url and Avatar to show in active users table
:profiles:
  # joebloggs:
  #   :url: https://www.example.com
  #   :avatar: https://secure.gravatar.com/avatar/ba1e13e0887456893b07e4ee8e78aece
